# Use an R-based Docker image
FROM rocker/rstudio:4.0.3
#FROM rocker/shiny:4.0.3

# Install necessary system libraries
RUN apt-get update && apt-get install -y \
    libcurl4-openssl-dev \
    libssl-dev \
    libxml2-dev \
    libjpeg-dev \
    libpng-dev \
    libhdf5-dev \
    libglpk40 \
    libxt-dev \
    libtiff-dev


# Install CRAN packages (excluding shiny and shinydashboard)
RUN R -e "install.packages(c('ggplot2', 'Matrix', 'rjson', 'cowplot', 'RColorBrewer', 'Seurat', 'grid', 'readbitmap', 'dplyr', 'data.table', 'doSNOW', 'hdf5r', 'remotes', 'tidyr', 'tibble', 'gridExtra', 'parallel', 'enrichR', 'gplots', 'e1071', 'psych', 'DT', 'stringr', 'pbapply', 'patchwork'), repos='http://cran.rstudio.com/')"

# Install Bioconductor manager
RUN R -e "if (!requireNamespace('BiocManager', quietly = TRUE)) install.packages('BiocManager')"

# Install Bioconductor packages
RUN R -e "BiocManager::install(c('rhdf5', 'DESeq2', 'edgeR'))"

# Install preprocessCore with specific configuration
RUN R -e "BiocManager::install('preprocessCore', configure.args='--disable-threading')"

# Install remotes package
RUN R -e "install.packages('remotes', repos='http://cran.rstudio.com/')"

# Install specific versions of packages using remotes
RUN R -e "remotes::install_version('shiny', version='1.6.0', repos='http://cran.rstudio.com/')"
RUN R -e "remotes::install_version('shinydashboard', version='0.7.1', dependencies = FALSE, repos='http://cran.rstudio.com/')"
RUN R -e "remotes::install_version('shinyWidgets', version='0.5.7', dependencies = FALSE, repos='http://cran.rstudio.com/')"



