# Use the official RStudio image as a base
FROM rocker/rstudio:4.1.2

# Install necessary system libraries
# USER root
RUN apt-get update && apt-get install -y \
    libcurl4-openssl-dev \
    libssl-dev \
    libxml2-dev \
    zlib1g-dev \
    libbz2-dev \
    liblzma-dev \
    libncurses5-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*




# Install CRAN packages
RUN R -e "install.packages(c('tidyr', 'foreach', 'doParallel', 'optparse'))"

# Install Bioconductor packages
RUN R -e "install.packages('BiocManager')"
RUN R -e "BiocManager::install(c('S4Vectors', 'GenomicAlignments', 'rtracklayer', 'Gviz', 'TxDb.Hsapiens.UCSC.hg19.knownGene', 'BSgenome.Mmusculus.UCSC.mm10', 'TxDb.Mmusculus.UCSC.mm10.knownGene', 'bamsignals'))"
