# Use rocker/rstudio image as base, which has R version 4.0.3
FROM rocker/rstudio:4.1.2

# Install necessary system libraries
RUN apt-get update && apt-get install -y \
    libcurl4-openssl-dev \
    libssl-dev \
    libxml2-dev \
    libjpeg-dev \
    libpng-dev \
    libhdf5-dev \
    libglpk40 \
    libxt

# additionals packages to install
    # libglpk40
    # libxt-dev

# Install required R packages
RUN Rscript -e "install.packages(c('ggplot2', 'Matrix', 'rjson', 'cowplot', 'RColorBrewer', 'Seurat', 'grid', 'readbitmap', 'dplyr', 'data.table', 'doSNOW', 'hdf5r', 'remotes'))"

# Expose port for RStudio
EXPOSE 8787

# Define the command to run when the container starts
CMD ["/init"]
